Update test file
bcdev/epr-api pull request #14
Opened 2021-08-23 15:15 UTC by dmarth

The referenced test file `MER_RR__2PNMAP20080412_084905_000002422067_00365_31982_0001.N1` is not publicly available. This PR replaces it with the new file `MER_RR__2PNRAL20100429_160201_000003102089_00040_42679_0001.N1` and makes the required changes.

Currently, the new file is available as a sample here:
http://www.brockmann-consult.de/beam/data/products/MERIS/MER_RR__2PNRAL20100429_160201_000003102089_00040_42679_0001.zip

Running `epr_main_test` produces the following output:
```
$ ./build/src/test/epr_main_test                                                              
bccunit: running test suite "main_test_suite" containing 4 test(s)
bccunit:   running test suite "test_suite_epr_api" containing 5 test(s)
bccunit:     running test case "test_get_element_value"
bccunit:     running test case "test_epr_open_product"
bccunit:     running test case "test_epr_get_dataset_id"
bccunit:     running test case "test_epr_read_record"
bccunit:     running test case "test_tie_points_ADS_4_4"
bccunit:   running test suite "test_suite_epr_core" containing 2 test(s)
bccunit:     running test case "test_epr_get_data_type_size"
bccunit:     running test case "test_epr_str_to_data_type_id"
bccunit:   running test suite "test_suite_epr_band" containing 1 test(s)
bccunit:     running test case "test_epr_parse_band"
I 2021/08/23 14:01:00 - ENVISAT Product Reader API, version 2.3
I 2021/08/23 14:01:00 - API successfully initialized
D 2021/08/23 14:01:00 - running on a little endian order architecture
D 2021/08/23 14:01:00 - product opened:
D 2021/08/23 14:01:00 - testdata/MER_RR__2PNRAL20100429_160201_000003102089_00040_42679_0001.N1
D 2021/08/23 14:01:00 - product size: 73908107
I 2021/08/23 14:01:00 - reading MPH
I 2021/08/23 14:01:00 - reading SPH
I 2021/08/23 14:01:00 - reading all DSDs
D 2021/08/23 14:01:00 - empty DSD seen (don't worry)
D 2021/08/23 14:01:00 - empty DSD seen (don't worry)
I 2021/08/23 14:01:00 - product type MER_RR__2PNRAL20100429_160201_000003102089_00040 (MERIS IODD7)
I 2021/08/23 14:01:00 - creating dataset identifiers
I 2021/08/23 14:01:00 - creating band identifiers
D 2021/08/23 14:01:00 - product scene raster size: 1121 x 1761
E 2021/08/23 14:01:00 - epr_get_band_id: band not found
bccunit:   running test suite "test_suite_epr_header" containing 1 test(s)
bccunit:     running test case "test_epr_parse_header"
W 2021/08/23 14:01:00 - product header: int integer value out of range
W 2021/08/23 14:01:00 - product header: unsigned int integer value out of range
E 2021/08/23 14:01:00 - epr_parse_header: invalid ascii header: keyword is empty
E 2021/08/23 14:01:00 - epr_parse_header: invalid ascii header: keyword not found
E 2021/08/23 14:01:00 - epr_parse_header: invalid ascii header: value not found
E 2021/08/23 14:01:00 - epr_parse_header: invalid ascii header: illegal value
E 2021/08/23 14:01:00 - epr_parse_header: invalid ascii header: illegal value
bccunit: test summary: 9 test case(s) total, 0 failure(s), 0 error(s)
```

The tests succeed, although there are some warnings and error messages printed by the API. I think they are at least partially intended by the tests as hinted by the `BC_ASSERT_NULL` invocations. Can those messages be safely ignored?

2021-08-23 16:01 UTC, avalentino requested changes
Looks good to me.
Just please also update the CHANGELOG.txt file.

2021-08-24 06:40 UTC, dmarth commented
Please see https://github.com/bcdev/epr-api/pull/14/commits/68063f9c9c0132e2aeaaf6aa6cefcbf7fa474ea2. Did I understand correctly that changes are collected to be part of a future 2.3 release?

2021-08-24 13:53 UTC, avalentino approved these changes

2021-08-24 13:53 UTC, avalentino commented
> Please see 68063f9. Did I understand correctly that changes are collected to be part of a future 2.3 release?

yes, correct

2021-08-24 13:53 UTC, merged

2021-08-24 13:54 UTC, avalentino commented
thanks @dmarth